### ISSUE TITLE
PDEX error

### ISSUE THREAD

**Issue by omerjerk** [processing/processing-android#132]
```
import android.view.MotionEvent;
void mouseDragged() {
 MotionEvent me = (MotionEvent) mouseEvent.getNative();
 // code here, like me.getHistorySize() and other Android-y things
}
```

Whenever I open the above sketch, I get the following error :

```
Cannot find "android.view" library. Line 1 in tab test
java.lang.NullPointerException
	at processing.mode.java.pdex.ASTGenerator.getSuggestImports(ASTGenerator.java:3309)
	at processing.mode.java.pdex.ErrorCheckerService.updateErrorTable(ErrorCheckerService.java:982)
	at processing.mode.java.pdex.ErrorCheckerService.checkCode(ErrorCheckerService.java:534)
	at processing.mode.java.pdex.ErrorCheckerService.run(ErrorCheckerService.java:332)
	at java.lang.Thread.run(Thread.java:745)

```

Any idea what does it mean ?
Is there a problem with Android mode ?

**Comment by benfry** [comment]
It's probably that android.jar needs to be added to the list of library JARs so that the error checker service is aware of it. Check out the recent change I made to the main PDE so the result of `getCoreLibrary()` was added and could be checked against. @Manindra29 wrote the `ErrorCheckerService` code and can probably provide other pointers on how it should be handled.

**Comment by omerjerk** [comment]
I'm not getting it.
Where do we need to add android.jar ?
Right now, getCoreLibrary https://github.com/processing/processing-android/blob/master/src/processing/mode/android/AndroidMode.java#L89 returns null.

**Comment by Manindra29** [comment]
Were you able to find out why the classPath object is not getting
initialized (as per our discussion)? Android.jar should be added to the
classPath object's search path.

**Comment by codeanticode** [comment]
I still get "Cannot find "android.view" library. Line 1 in tab sketch_150817b", but not NPE after merging PR https://github.com/processing/processing-android/pull/134

**Comment by omerjerk** [comment]
I'm also getting this.

**Comment by codeanticode** [comment]
see my last comment in https://github.com/processing/processing-android/pull/134

**Comment by Manindra29** [comment]
I found the cause of the NPE bug. It's because of a race condition. The classPath variable (which was null here) is initialised in ASTGenerator.loadJars(), which is called from ErrorCheckerService.prepareCompilerClasspath() in a separate thread. Due to a race condition, when a sketch is just being loaded, classPath is sometimes accessed before it has even been initialised and thus the NPE is thrown.

**Comment by Manindra29** [comment]
I can add a null check as a stopgap fix, but this probably needs a second look.
