### ISSUE TITLE
Select target SDK shows two SDKs selected simultaneously

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#148]
With the latest mode:

![image](https://cloud.githubusercontent.com/assets/62246/9992624/9ecb2aa8-6049-11e5-8b4c-c2fe24dcb918.png)

**Comment by omerjerk** [comment]
Hi @codeanticode 
I'm not able to reproduce this error because Google has removed API M form the SDK manager now.
So, as of now, this bug won't show up who doesn't already have M Preview SDK installed.

I think that the error is most probably because both the SDKs have same API level.
I'll try to see if I can think of a proper fix. I think, as of now, we use the API level as the key to distinguish different SDKs in that menu.

**Comment by codeanticode** [comment]
Is there other information we can use to differentiate two different SDK's with the same API level? Anyhow, seems it can only happen exactly under these circumstances (an SDK and its pre-release both installed simultaneously in the same machine).

**Comment by omerjerk** [comment]
I can differentiate on the basis of the Android version represented by a particular API. for e.g. 4.0.4, 4.4.2, M etc.

I'll send a pull request.

**Comment by codeanticode** [comment]
Tested with Android Android 5.1.1 and M (both 22) installed on my system, and your patch solves the issue. Thanks!
