### ISSUE TITLE
Better fullscreen mode

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#207]
Navigation bar should not be visible when running sketch in full screen mode. PR3 includes some changes that hide the bar using the new [immersive API](http://developer.android.com/training/system-ui/immersive.html) available in 4.4 and higher, otherwise it simply sets the [SYSTEM_UI_FLAG_HIDE_NAVIGATION](http://developer.android.com/reference/android/view/View.html#SYSTEM_UI_FLAG_HIDE_NAVIGATION) flag.

**Comment by evshellshear** [comment]
@codeanticode in fullscreen mode, after the navigation bar is swiped in, it no longer disappears (as expected). I think on line 504 in PApplet.java, you also want View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY as well to get your desired behavior? Not totally sure. I just see that the nav buttons won't go away (after swiping left) even after trying to mess with my manifest (i.e. changing android:theme="@android:style/Theme.NoTitleBar.Fullscreen)

**Comment by evshellshear** [comment]
@codeanticode if you think my suggestion is right and you want to try adding the additional View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY flag and send me a link to a new AndroidMode zip, I'll install it and double check that it works.

**Comment by codeanticode** [comment]
The android-core.zip file should be enough. Replace the one inside the AndroidMode folder with the one I'm attaching here. I added the View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY to the visibility, as you suggested. Let me know if it works.

[android-core.zip](https://github.com/processing/processing-android/files/225889/android-core.zip)

**Comment by evshellshear** [comment]
Awesome. Will do. Just going to bed now but will try tomorrow when I wake
up.

Thanks

**Comment by evshellshear** [comment]
@codeanticode thanks for that. It works like a charm now!

**Comment by codeanticode** [comment]
Excellent!

**Comment by evshellshear** [comment]
@codeanticode sorry to open up this issue again but the full screen mode doesn't seem to work as it should. I am getting a similar type of behavior to the following thread (which also suggests a solution):
http://www.jericdy.com/blog/2014/01/09/proper-way-to-use-full-screen-immersive.html

Except that it happens for me when you press the home button while the game is "loading" either the Hang or the Catch game, and then open the game again. The navigation bar is then permanently there. On my phone I don't get the issue with volume controls like in the above thread but the end result of reopening the app is the same.

**Comment by rich-gg** [comment]
Since RC3 my app run flawlessly 

 for info, the manifest for my app uses IMMERSION mode like so:
decorView.setSystemUiVisibility(
View.SYSTEM_UI_FLAG_LAYOUT_STABLE
| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
| View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
| View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
| View.SYSTEM_UI_FLAG_FULLSCREEN
| View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}

**Comment by evshellshear** [comment]
Thanks for the feedback and what you wrote is quite interesting. Two
questions:

1) are you able to reproduce the issue at all either via the volume rocker
(a la link i posted) or via exiting the app with home or back button and
then returning to the app?

2) how do you use a decorView in your processing app? In the draw or setup?
I have tried but I get an error. I didn't think I was allowed to touch that
if I use the processing Android mode. If you could post a code example that
would be awesome.

Thanks for comments.
On May 1, 2016 10:30 PM, "rich.gg" <notifications@github.com> wrote:

Since RC3 my app run flawlessly

for info, the manifest for my app uses IMMERSION mode like so:
decorView.setSystemUiVisibility(
View.SYSTEM_UI_FLAG_LAYOUT_STABLE
| View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
| View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
| View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
| View.SYSTEM_UI_FLAG_FULLSCREEN
| View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);}

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/processing/processing-android/issues/207#issuecomment-216038821>

**Comment by evshellshear** [comment]
@codeanticode have you had a chance to test this issue?

**Comment by codeanticode** [comment]
Not yet, but will try to do it soon.

**Comment by codeanticode** [comment]
The issue with when pressing the volumen buttons seems to be a bug in KitKat, it doest not happen in 6.0.1. Another thing that did happen was that the navigation bar remained visible in full screen mode when the app rotates upon orientation change, that is fixed by reseting the visibility on resume https://github.com/processing/processing-android/commit/dd60471d17b018bd159cbf8983ed4fbc965bd139

However, there is still one minor issue, that seems to be due to a bug in 6.0.1. See the last comments in this thread: https://code.google.com/p/android/issues/detail?id=170752

**Comment by evshellshear** [comment]
Ok great. Thanks for that. I assume the work around suggested in the thread
is not desirable in the processing code base but how can I add it to my
code? In the setup or draw part? I'm not a pro at this, so could you give a
code snippet if you get a chance please?

Thanks!

**Comment by codeanticode** [comment]
setOnSystemUiVisibilityChangeListener() is a method defined in the View class. I believe you should call it on the surface view associated to the sketch, something like this:

```java
import android.view.View;

void settings() {
  fullScreen(P2D);
}
  
void setup() {
    getSurfaceView().setOnSystemUiVisibilityChangeListener(new View.OnSystemUiVisibilityChangeListener() {
    @Override
    public void onSystemUiVisibilityChange(int visibility) {
     // ...
    }
    });      
}
  
void draw() {
}  
```

but haven't tested it.

**Comment by evshellshear** [comment]
Awesome. I'll play around with that. Thanks again.
