### ISSUE TITLE
Could you embrace Ketai library as a subproject of Processing-Android?

### ISSUE THREAD

**Issue by q2dg** [processing/processing-android#228]
This library seems pretty abandoned and it's a pity. It would be the perfect complement to make Processing-Android a really complete environment to write Android-based applications, and meanwhile keeping its simplicity. Students could get rid of AppInventor!!

**Comment by codeanticode** [comment]
I'm in touch with the authors of Ketai, and they confirmed that the project is active. If you are experiencing specific issues with it, please report them in their [GitHub page](https://github.com/ketai/ketai/issues).

**Comment by q2dg** [comment]
Well, I turn again. 

If Ketai isn't, what about (at least ) try integrating  https://github.com/arduino/BtSerial?

It is a library to give Bluetooth capabilities to processing-android (in "desktop" processing it doesn't matter because we can use Bluetooth through Serial communication but in Android is not so easy . 

I have written more reasoning in https://github.com/arduino/BtSerial/issues/3#issue-167737515

Thanks.

**Comment by q2dg** [comment]
Well...if not doing any commit from two years ago is being an "active" project, maybe we should check the definition of "active". 

If Android Mode isn't capable to access sensors's mobile device I think it is pretty useless

**Comment by codeanticode** [comment]
I contacted the ketai team recently, and they are working on a new release of the library that will be compatible with the latest versions of the Android mode. 

For the time being there are no plans to bring ketai into the core. Since it is available through the Contributions Manager, I don't think that'a big issue. Also, using the Android SDK directly from a Processing sketch to access sensors is not very difficult, and we have written a number of tutorials covering the topic in some detail ([sensors](http://android.processing.org/tutorials/sensors/index.html), [permissions](http://android.processing.org/tutorials/location/index.html), [wallpapers](http://android.processing.org/tutorials/wallpapers/index.html), [watch faces](http://android.processing.org/tutorials/watchfaces/index.html)).

A core sensor library may be nice to have at some point, so I'm tagging this issue as an enhancement.

**Comment by q2dg** [comment]
Thanks a lot!

**Comment by q2dg** [comment]
"I contacted the ketai team recently, and they are working on a new release of the library that will be compatible with the latest versions of the Android mode."

Well...no news still...

**Comment by codeanticode** [comment]
The ketai.zip package in the [downloads folder](https://github.com/ketai/ketai/tree/fixes/downloads) of the fixes branch, although not final, is compatible with the most recent betas of the android mode.
