### ISSUE TITLE
Unable to build sketch for android 2.3.3 (API 10)

### ISSUE THREAD

**Issue by Harvie** [processing/processing-android#316]
I install SDK for API 10 in SDK manager, but it does not show up in processing. It only shows me android 3.0 and newer...

**Comment by Harvie** [comment]
API installed
![image](https://cloud.githubusercontent.com/assets/276504/24423999/48e26492-13ff-11e7-9888-21970395c332.png)

Does not show in processing. Even after restart:
![image](https://cloud.githubusercontent.com/assets/276504/24424028/644716b0-13ff-11e7-80cb-f0e6f4e0bd86.png)

Can i build for android 2.3(.3) using newer SDK? There's no way to set minimal api for app in processing.

**Comment by codeanticode** [comment]
@Harvie Minimum Android SDK supported by Processing is 16.

Unfortunately, due to GLES bugs in Android 2.x, and the small fraction of users on any version of Android prior to Jelly Bean (2%, according to the[ latest Google Dashboards](https://developer.android.com/about/dashboards/index.html)), we decided to make the cut at 16. Since we are a small team of core developers maintaining the mode, we don't have enough resources to properly support all versions of Android.

**Comment by Harvie** [comment]
Oh i see. Can you please put this info somewhere to be easily noticable?? eg. readme.md in git and to wiki. so people like me are not wasting time with old phones. That would save me some trying... It's bit missleading, because SDK manager allows you to install older SDKs (which makes sense) but it's not obvious that these will not be loaded by processing itself and why...

BTW i tried with newer android phone (IIRC it was android 5 or 6) and everything went great, but when i've clicked on the installed app it only blinked fullscreen black and disappeared/crashed instantly... so there's probably another problem. It was working in java mode. it was very simple sketch, just drawing some elipses and text.
