### ISSUE TITLE
Access current fragment in latest Android Mode (4.0b7)

### ISSUE THREAD

**Issue by kfrajer** [processing/processing-android#345]
Did PApplet extended either Activity or fragment in AndroidMode 3.0.2? I notice in the latest Androidmode (4.0beta7 - ?), the PApplet extends Object and then I assume the fragment extension is associated with the PSurface object? I am referring to [Line 57 and 62](https://github.com/processing/processing-android/blob/master/core/src/processing/core/PApplet.java#L57)

I am trying to implement the Menu feature as depicted in the following [forum post](https://forum.processing.org/two/discussion/18606/creating-native-android-menus-in-processing-android-mode#latest) and Android Devs documentation: [Menus](https://developer.android.com/guide/topics/ui/menus.html#options-menu). Notice that the code works for AM3.0.2. For AM4.0b7 I get the error attached to the end of this post.

I appreciate your assistance if we start by addressing my first question and maybe an approach to get a handle to the PSurface to access and override their fragment's life cycle functions ( I am totally assuming PSurface extends a Fragment-like class... so please correct me if I am wrong).

Kf

=============ERROR MSG REPORT running forum sample code on Android Mode 4.0beta7:

> Generating BuildConfig class.
> 
> -pre-compile:
> 
> -compile:
>     [javac] Compiling 5 source files to C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\bin\classes
> ----------
> 1. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 148)
> 	super.onCreateOptionsMenu(menu, inflater);
> 	      ^^^^^^^^^^^^^^^^^^^
> The method onCreateOptionsMenu(Menu, MenuInflater) is undefined for the type PApplet
> ----------
> 2. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 176)
> 	return super.onOptionsItemSelected(item);
> 	             ^^^^^^^^^^^^^^^^^^^^^
> The method onOptionsItemSelected(MenuItem) is undefined for the type PApplet
> ----------
> 3. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 184)
> 	View onCreateView (LayoutInflater inflater, 
>   ViewGroup container, 
>   Bundle savedInstanceState) {
> 	     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> The method onCreateView(LayoutInflater, ViewGroup, Bundle) of type MenuButton must override a superclass method
> ----------
> 4. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 187)
> 	super.onCreateView(inflater, container, savedInstanceState);
> 	      ^^^^^^^^^^^^
> The method onCreateView(LayoutInflater, ViewGroup, Bundle) is undefined for the type PApplet
> ----------
> 5. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 188)
> 	setHasOptionsMenu(true);
> 	^^^^^^^^^^^^^^^^^
> The method setHasOptionsMenu(boolean) is undefined for the type MenuButton
> ----------
> 6. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 194)
> 	super.onCreate(savedInstanceState);
> 	      ^^^^^^^^
> The method onCreate(Bundle) is undefined for the type PApplet
> ----------
> 7. ERROR in C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\src\processing\test\menubutton\MenuButton.java (at line 195)
> 	setHasOptionsMenu(true);
> 	^^^^^^^^^^^^^^^^^
> The method setHasOptionsMenu(boolean) is undefined for the type MenuButton
> ----------
> 7 problems (7 errors)
> 
> BUILD FAILED
> C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\build.xml:22: The following error occurred while executing this line:
> C:\Users\C\AppData\Local\Temp\android5625168163671818089sketch\build.xml:35: Compile failed; see the compiler error output for details.
> 
> Total time: 7 seconds

**Comment by codeanticode** [comment]
PApplet used to extend Android's Fragment in 3.0.2, see [here](https://github.com/processing/processing-android/blob/android-0253-v3.0.2/core/src/processing/core/PApplet.java#L67). As you noticed, it is now a subclass of Object, the reason for this is that the architecture of the mode had to be modified to accommodate wallpaper and watch face services, as well as VR apps. In general terms, what the mode now does is to create an instance of the sketch class, and add it to the containing fragment or service. This takes place in the launch activity that is generated automatically from a template file:

https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/templates/FragmentActivity.java.tmpl

In the case of wallpapers and watch faces, it is a service instead of an activity that instantiates the sketch, but also generated from a template file:

https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/templates/WallpaperService.java.tmpl

https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/templates/WatchFaceService.java.tmpl

but these are not really relevant in this discussion, since the menu API exists only for activities.

So the problem more generally is how to override the life cycle functions in Activity and/or Fragment, since PApplet is no longer descendant of neither. What I started doing as a "quick" solution for certain special cases (more specifically, to allow libraries such as [Ketai](https://github.com/ketai/ketai) to insert themselves into the Activity lifecycle properly) was to add a few methods such as [onCreate()](https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/core/src/processing/core/PApplet.java#L575), [onDestroy()](https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/core/src/processing/core/PApplet.java#L579), and [onActivityResult()](https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/core/src/processing/core/PApplet.java#L584), which are called from the corresponding [event handling method in PFragment](https://github.com/processing/processing-android/blob/android-0262-v4.0-beta9/core/src/processing/android/PFragment.java#L224).

So one approach would be to keep adding Activity methods to PApplet, like those needed to create menus, and calling them from the containing fragment (the menu API is in fact available in Fragment), but some other life cycle methods, such as [onNewIntent()](https://developer.android.com/reference/android/app/Activity.html#onNewIntent(android.content.Intent)), as only defined for Activity. So in those cases, they should be added to the main activity template, from where one can also call the corresponding method in PApplet.

Other approach, to avoid adding all these methods to PApplet could be to extract all onXxxx() methods defined by the user in PApplet, and copy them to the main activity... but kind of messy, since these methods could be using variables defined in the sketch.

Maybe, at leas to keep things organized, I could add an ActivityAPI interface to the [android package](https://github.com/processing/processing-android/tree/android-0262-v4.0-beta9/core/src/processing/android) in the core library, which contains all the Android-specific stuff, holding the declaration of all these Activity event handlers, and implement this interface in PApplet.

Finally, you can also get a hold of the main activity as well as the fragment from the sketch, by calling:

```
import android.app.Activity;
import android.support.v4.app.Fragment;

void setup() {
  Activity activity = getActivity();
  Fragment fragment = (Fragment)getSurface().getComponent();
}
```

But I'm not sure if this would be of any help, since I don't know if you can implement the event handlers in runtime.

I'm adding @danielsauter from the Ketai project, so they can weight on this as well.

**Comment by kfrajer** [comment]
Thanks for your reply @codeanticode. I will review your comments and give it some thought. The changes are deep. I was comfortable accessing the onXXXXX methods directly. From your comments, I'm not sure what would be the best approach... On a side topic and related to Ketai. Let's assume one comes up with a solution X. Do you see _one_ version of ketai working for older Android modes and a new version of ketai for the latest? 

kfrajer

**Comment by codeanticode** [comment]
Yes, the current version of Ketai will be the one to use with older releases of the Android mode, and all upcoming versions should be paired with the latest release of the mode.

**Comment by codeanticode** [comment]
@kfrajer I'm implemented the menu api in PApplet, and the sketch your posted on the forum works without error but I don't see any menu. I also tried with the version 3.0.2 of the mode, but don't see the menu either. Am I missing something?

**Comment by kfrajer** [comment]
@codeanticode I get the menu when you press the "menu" button aka. the physical button. I referred to the buttons at the bottom of the screen as MENU, HOME and BACK. I can send you a couple of screenshots of what it suppose to appear if needed (one [sample](https://cdn.theunlockr.com/wp-content/uploads/2012/05/shot_000040.png) from the web). If you have the code, I can run it tomorrow and give you feedback. 

Kf

**Comment by codeanticode** [comment]
On devices running Android 5 or newer w/out hardware buttons (like the Nexus phones), I don't have a menu button... Not clear how to access it, if possible at all. For instance, this [WhatsApp FAQ](https://faq.whatsapp.com/en/android/21228643) explains that, in that case, you must tap and hold the app switch, but when I do that, it either switches between the current and last app, or get into a split screen mode. Comments in this [stackoverflow thread](https://stackoverflow.com/questions/19746314/menu-button-doesnt-show-on-nexus-7) say that:

* If target API version is less than 11 it is shown on all devices
* If target version is 11, 12, or 13 (i.e. tablet-only Honeycomb) Android assumes that your app has been designed for tablets and won't show a legacy button on tablets, but will on phones
* If target is 14 or above (ICS and above), Android assumes your app is designed for tablets and phones and so the legacy button isn't shown.

and that :

```
On Android 3.0 and higher, items from the options menu are presented by the action bar as a combination of on-screen action items and overflow options. Beginning with Android 3.0, the Menu button is deprecated (some devices don't have one), so you should migrate toward using the action bar to provide access to actions and other options.
```

The latest betas of the mode use minimum sdk version 16, so this means the menu should not be visible...

**Comment by kfrajer** [comment]
Thanks for looking into this.  I am running Android version 5.0.1 (API 21) on a Samsung Galaxy S4 and I was able to get the menu feature using the code from the forum. However, I don't know how I got access to it based on your comments. Would the Menu feature fall under the action bar feature? From previous post searches, I understood toolbars should be used instead of menu options (and action bars [?] ). TBH, I am not sure what is the best way forward regarding this and I have very limited experience to be able to contribute to this topic. I have to say though, having this feature, and to be able to get it working, was a very neat experience as it was very few lines of code to get a full dropdown menu in action.


Let me know if I could assist in any way.


kfrajer


________________________________

**Comment by codeanticode** [comment]
I will look into the action bar feature, and will report back. Perhaps the menu works for you on the Galaxy phone (even though the API level is 21) due to Samsung's "unique" Android UI customizations, but I would not rely on those when deploying your app across a wider group of devices.

**Comment by codeanticode** [comment]
The next release of the mode (hopefully a "release candidate" before pushing it through the Contributions Manager) will allow you to add your menu in the "action bar", but first you will have to change the default android:theme property in the manifest file from "@style/Theme.AppCompat.Light.NoActionBar.FullScreen" to "@style/Theme.AppCompat.Light". Running the sketch posted in the forum would look like this:

![image](https://user-images.githubusercontent.com/62246/28180425-12125968-67d3-11e7-94d2-05df4d96ce73.png)

**Comment by kfrajer** [comment]
@codeanticode  That is pretty neat, thank you!

Kf
