### ISSUE TITLE
How to create a wallpaper without dying in the attempt.

### ISSUE THREAD

**Issue by DanielAbalde** [processing/processing-android#360]
It is being a nightmare for me to configure everything correctly to create wallpapers. To the point that I can no longer open the SDK/AVD Manager from processing, because something I did wrong sometime I guess, (but I can open them from Android SDK Tools anyway).

The official docs have me confused a lot, there are no clear examples out there (or I have not found them) that say this and this must be done. So, can someone be so kind as to tell me how to set everything up? For example, at this day:

1) Which version of Processing is recommended for Wallpapers? 
2) What version of the android mode and android SDK/API?
3) What version of android tools i need?
4) I have the right versions, _now what_?
5) In what folder do I have to put the tools?
5) Where is the android sdk to which processing refers? Can be C:\Program Files (x86)\Android\android-sdk ? If is, and there I have to replace the tools there, how do I avoid manipulating the original sdk?
6) I have the 19, 21,22,23 and 25 APIs of android, but where are they filed usually in windows? Is it advisable to uninstall some of them?

Thanks in advance!

**Comment by danieltorrer** [comment]
@DanielAbalde
 I'll share you my experience. 
I'm using lastest version of processing 3.3.5 and API 25 of android.
Using Android Mode 0263
If you installed the sdk through android studio the default location of the sdk (in WIN) is User/youruser/local/AppData/Local/Android/sdk 
It's ok if you have more than one API

You need to select the android mode and then go to _Android -> Wallpaper_
I suggest to open an example of Wallpapers in _File -> Examples ->Topics -> Wallpapers_ to see how it's done

Currently in my windows machine I'm facing issue #307 but in OSX works fine. Haven't tested in another windows machine.

Hope that helps

**Comment by DanielAbalde** [comment]
Thank you very much for your answer @danieltorrer ,
But I'm still at the same point. When I run the example the following error is displayed:

BUILD FAILED
C:\Users\Dani\AppData\Local\Temp\android1698180558604241926sketch\build.xml:81: Cannot find C:\Users\Dani\AppData\Local\Android\sdk\tools\ant\build.xml imported from C:\Users\Dani\AppData\Local\Temp\android1698180558604241926sketch\build.xml

Which is the same thing that happened to me before. I suppose it is due to the tools that need to be downloaded separately. So, where should I place these tools? In User/youruser/local/AppData/Local/Android/sdk?(I already tried that) or in the android mode folder?

Another problem I have is that SDK and AVD manager do not open, how can I fix this? I have reinstalled the android mode and it remains the same. When I did, I was not asked to select the SDK, so maybe I did not delete it correctly before reinstalling the mode?

**Comment by codeanticode** [comment]
@DanielAbalde the problem is that the latest versions of the Android SDK no longer include the ant build scripts, as well as the android tool (which runs the SDK and AVD manager), as it is reported in issue #307. You can either download the SDK manually, making sure that you use the following versions of the tools:

* build tools: 25.0.3
* platform tools: 25.0.3
* sdk tools: 25.2.5

or install [beta 10](https://github.com/processing/processing-android/releases/tag/android-263) of the mode, which downloads exactly those versions of the tools.

We are currently working on the next "stable" release of the mode to publish through the Contributions Manager, which solve all these issues, and should be ready in the coming weeks. Thanks for your patience!
