### ISSUE TITLE
Progress bar in SDK updater is indeterminate

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#362]
Right now, the progress bar in the SDK updater is set to indeterminate mode, because the getFraction() method in the ConsoleProgressIndicator object used in the query and download tasks returns 0. 

[This code](https://github.com/JetBrains/android/blob/master/android/src/com/android/tools/idea/welcome/wizard/InstallComponentsPath.java) from the [Android Plugin for IntelliJ IDEA](https://github.com/JetBrains/android) can help understanding more advanced users of the progress indicator and the download functionality:

My impression is that the current progress has to be set somehow using progress.setFraction(), so it can then can be retrieved with progress.getFraction().

**Comment by DeerajTheepshi** [comment]
@codeanticode , 
The link that "This code" refers to has been removed(404 Error). Can you check it ?

**Comment by codeanticode** [comment]
@DeerajTheepshi thanks for flagging this, will take a look shortly

**Comment by DeerajTheepshi** [comment]
@codeanticode 
Is there any documentation for ConsoleProgressIndicator.java (and other API / SDK classes) , other than going through the jar file?

**Comment by DeerajTheepshi** [comment]
@codeanticode Is there any official documentation for the sdk repo / api  methods like **ConsoleProgressIndicator** ? Right now i'm using a decompiler to read java code from the jar file.

**Comment by DeerajTheepshi** [comment]
@codeanticode and @kfrajer  , The getFraction function works . I'm not sure why this issue was raised , but it seems to be working fine. The setFraction method is taken care by the android libraries. So it does not pose a problem. The only issue is that the same consoleProgress object is used for 3 different process :
- Loading the repo
- Preparing the installer files and the install process itself
- Completion of the install process

As a result of which, the progressBar would load from 0 ,three times. We could notify the user about these three stages via the status text on the updater.
