### ISSUE TITLE
some Chars from the keyboard are seen as -1

### ISSUE THREAD

**Issue by Wimmie13** [processing/processing-android#408]
The virtual or soft keyboard returns a char. On Windows if you press capitel z you get capitel z with code 35. On android you get an unknow character with the value of -1. This is for all capitalized letters and chars like ? and !.

**Comment by codeanticode** [comment]
@Wimmie13 I have added a few missing key constants in commit https://github.com/processing/processing-android/commit/3b137f266b55dfc09cbfd5a8fbc9b9ce1e04f64c, so now keys such as (left) shift, enter, delete, and tab should be recognized. I tested the values returned by the soft keyboard on a N5X phone and a Samsung Tab 4 tablet. The N5X uses the Google keyboard (Gboard) app, and the Tab 4 the Samsung keyboard app. It seems that they generate different events, which in fact is mentioned in the [Android Developer docs](https://developer.android.com/reference/android/view/KeyEvent.html): 

_"As soft input methods can use multiple and inventive ways of inputting text, there is no guarantee that any key press on a soft keyboard will generate a key event: this is left to the IME's discretion, and in fact sending such events is discouraged."_

In the case of the N5X with the Gboard, pressing shift once and then a letter key generates an expected sequence of SHIFT and the corresponding uppercase character. If shift is pressed twice quickly, shift gets locked so you then get uppercase characters without a SHIFT. However, this is not the case with the Samsung keyboard, even if you lock the shift, you still get a SHIFT character before every uppercase letter. I then installed the Gboard app on the Tab, and set it as the active keyboard, and the returned characters are the same as in the N5X. 

In order to recognize keys that are not included as a Processing constant, you can always import the android.view.KeyEvent package in your sketch and use all of its key codes.
