### ISSUE TITLE
No way to intercept the back button exiting the app

### ISSUE THREAD

**Issue by dzaima** [processing/processing-android#414]
I can't seem to find a way to stop a Processing app from closing on clicking the back button - I'm trying to implement a page/menu system and the back button exiting no matter what is.. annoying.

In an older Processing version, there was `onBackPressed`, but in [this](https://github.com/processing/processing-android/commit/45b87f0e7f1237e276c216dad03bd24e862a945f?diff=unified#diff-8e1673658a2441fe0753dd2b25e85025) commit, it was commented out. I've tried overriding `onDestroy`, `keyPressed`, `keyReleased`, `stop` on all the renderers with no success.

Is there a way to do this?

**Comment by codeanticode** [comment]
Thanks for this observation. The problem is with the transition to Fragment-based sketches, the onBackPressed() method could no longer be used, as it is not defined for Fragments. It could still be added in the main activity that contains the Processing sketch, but it is not immediately obvious what the best implementation could be. One possibility could be to use introspection to determine if the sketch has a function with some predetermined name, such as back(). If it does, call that function, otherwise continue with the default implementation of onBackPressed, so the activity quits:

```
public class MainActivity extends AppCompatActivity {

  @Override
  public void onBackPressed() {
    if (sketch != null) {
      // check if sketch has a method call back(), etc.
      return;
    }
    super.onBackPressed();
  }
}
```

**Comment by codeanticode** [comment]
I think onBackPressed() could be added to [ActivityAPI](https://github.com/processing/processing-android/blob/master/core/src/processing/android/ActivityAPI.java), which already contains a number of methods that are available in Activity and useful to implement in PApplet.

**Comment by codeanticode** [comment]
Implemented with https://github.com/processing/processing-android/commit/0f5466925949798cf8882f91482d55aefa62d545

**Comment by dzaima** [comment]
What's the proper way now to exit from the sketch if `onBackPressed` is overridden since `exit()` doesn't exist?
