### ISSUE TITLE
The Android SDK could not be loaded.

### ISSUE THREAD

**Issue by kyumdlab** [processing/processing-android#418]
![error](https://user-images.githubusercontent.com/33537416/34283524-2b2dcb5e-e707-11e7-847d-3ddf96622a17.PNG)

I use the "Locate SDK path manually" and "Download SDK automatically" option, there will be "The Android SDK could not be loaded" error message.

How do I load the Android SDK?

(I use Processing 3.3.6 version)

**Comment by codeanticode** [comment]
Thanks for reporting this problem. Is this your first time using the android mode and trying to install the SDK?

**Comment by kyumdlab** [comment]
Yes.

I installed Platforms-26 using Android Studio's SDK Manager, now it is work. (Android Studio default is to install Platforms-27)

But "Download SDK automatically" still does not work.

**Comment by pdcxs** [comment]
I use windows 10, processing 3.3.6 version, 64bit, even set the location of SDK manually, it doesn't work. I'm sure I have installed platform 26

**Comment by KeesR** [comment]
Using windows 10, processing 3.3.6.
When setting the location of SDK manually, during installation, I get same problem.

Log file in C:\Users\Kees\AppData\Roaming\Processing\console (attached
[171231_112040.err.log](https://github.com/processing/processing-android/files/1595120/171231_112040.err.log)) shows several BadSDKExceptions,
- One is about not finding a wearable location - here the location as requested in AndroidSdk.java (in extras/google) seems to be moved to extras/android on my installation (and the internal structure seems changed as well)
- Another is about  not finding the AVD manager - the location as requested (tools/bin) seems to be moved to android-sdk root folder on my installation
Resolved both issues (create required empty wearable dir, and bat file for avdmanager in correct folder) and now android mode is installed.

However due to changed structure of wearable folder, building the sketch will fail.
[wear API 2.0.0 seems to be integrated in the API 26.0, looking at the build exception].

**Comment by Bedjes** [comment]
Hi ! I'm looking since this morning how to succes and I did it ! For every one who need help i will say what to do :

1 : Download _Android Studio_ for ur OS here : https://developer.android.com/studio/index.html
2 : Install _Android Studio_
3 : Open _Android Studio_, clik to _Configure_, _SDK Manager_, _Appearence & Behavior, _System Settings_ , _Android SDK_
4 : Download the _Android 8.0 (Oreo)
5 : Remember the path on the top of the screen _Android SDK Location_
6 : Open Processing
7 : On the top right corner clik on _JAVA_ --> add modes --> _download Android Mode_ then choose the _Android Mode_ insted of _JAVA_
8 : select the path who is indicate step 5

Normaly it's done !

**Comment by F4Tornado** [comment]
That's what I did too, I opened an issue reporting the same thing, got the same answer, and made a stackoverflow answer using it with less detail.

**Comment by codeanticode** [comment]
Fixed with https://github.com/processing/processing-android/commit/b4145e192b5ca7f6795f80a1b9ffdad26dedc215

**Comment by PixsaOJ** [comment]
I still had to download sdk-tools and 26 API
