### ISSUE TITLE
The Android SDK could not be loaded

### ISSUE THREAD

**Issue by F4Tornado** [processing/processing-android#421]
I'm using Windows 10 Home edition
I'm also using Android mode 4.0

In the middle of downloading the Android SDK, It stops downloading and says The Android SDK could not be loaded, unless it loads really quickly after 30%, then it happens when its done loading.

I tried restarting already.

**Comment by kgates-github** [comment]
I had a similar issue with mac OS 10.13.2 with processing 3.3.6. After selecting "download SDK automatically", the progress bar in the SDK download dialog box goes to 28%, then the "bad news" error message appears.

**Comment by revolver038** [comment]
I had too. After hours of search, eventually figured it out.
That is why I'd downloaded android studio manually and using its sdk manager downloaded API 26 platform. Then instead of download, located to the path to Android SDK. It is also could be seen in **File > Preferences > C\...\ preferences.txt**  like this: android.sdk.path=C:\Users\MyName\AppData\Local\Android\Sdk

that's it.

**Comment by F4Tornado** [comment]
I'm going to try this...

**Comment by F4Tornado** [comment]
It seems to have worked! I'll actually try it tomorrow, its late.

**Comment by F4Tornado** [comment]
Yes it did work!

**Comment by revolver038** [comment]
Good then, issue has been solved!

**Comment by F4Tornado** [comment]
Forgot to close it.

**Comment by F4Tornado** [comment]
In more detail: #418

**Comment by Yashwanthd1998** [comment]
iam having the same problem..i cannot load sdk manually,HELP!

**Comment by cjdg** [comment]
Can confirm is happening again both linux and windows,
