### ISSUE TITLE
 createShape(TEXT, "HELLO", 25, 35, 50, 50);

### ISSUE THREAD

**Issue by rich-gg** [processing/processing-android#423]
Wouldn't it be nice to have the TEXT type of PShape objects ?

Or is there already a trick to construct PShape GROUPs featuring some TEXT elements that you can control ?

**Comment by codeanticode** [comment]
Thanks for the suggestion. In Java mode you can use the SHAPE text mode, although is not integrated with PShape. However, the SHAPE mode for text is not available on Android, since it depends on AWT functionality.

I will not be able to work on this enhancement at this time, but PRs are welcome. At the moment, one way to do this, could be to create your text shapes with some 3D software and then load them into Processing as OBJ files.
