### ISSUE TITLE
ConcurrentModificationException on back press

### ISSUE THREAD

**Issue by dzaima** [processing/processing-android#473]
It seems that the `onBackPressed()` function is called parallel to `draw()` which can easily cause a `ConcurrentModificationException`. While this can be easily worked around, realizing that it's `onBackPressed`s fault can be hard.

Example code that crashes (usually) if the back button is pressed:
```java
import java.util.Collections;
class Obj {
  ArrayList al = new ArrayList<Integer>();
  Obj() {
    for (int i = 0; i < 1000000; i++) {
      al.add(i);
    }
  }
  void process() {
    Collections.sort(al);
  }
}
Obj obj = new Obj();

void draw() {
  obj.process();
}
void onBackPressed() {
  obj.process();
}
```

**Comment by codeanticode** [comment]
@dzaima  Fixed with https://github.com/processing/processing-android/commit/79b38d16aeb29edfe9425fb0cf21a9ac88bb0fc1

Now you have to implement the backPressed() function in your sketch (not onBackPressed()) to avoid quitting when the back key is pressed. This function gets called from the animation thread, so this should solve the concurrency exception.

**Comment by dzaima** [comment]
@codeanticode is there a way to stop the sketch with `backPressed` overriden (except the crude `System.exit(0);`)? The code for `exit()` is commented out.

**Comment by codeanticode** [comment]
I think the correct way is to call to call getActivity.finish()
