### ISSUE TITLE
cameraUp gives me a white line on a black background.

### ISSUE THREAD

**Issue by clankill3r** [processing/processing-android#503]
I was trying some of the examples and they work fine.
Hover the one about `cameraUp`:

```java
import processing.vr.*;

void setup() {
  fullScreen(STEREO);
  cameraUp();
} 

void draw() {
  box(300);  
}
```

Gives me a black background and a line that looks a bit like if you would draw a line like this:
(Remember this is a box!)

```java
stroke(255);
strokeWeight(3);
line(width/2, height * 0.6, width/2, height);
```

**Comment by codeanticode** [comment]
Hi, the example in the reference is missing a background() background call, the following should display the box as expected:

```
import processing.vr.*;

void setup() {
  fullScreen(STEREO);
  cameraUp();
} 

void draw() {
  background(0);
  box(300);  
}
```

The reason VR does not work with a background call is because the Processing renderer does a number of tricks to allow keeping the previous frame when not clearing the screen, but those are not compatible with VR rendering.
