### ISSUE TITLE
Fetch Process continues even after SDK updater window is closed

### ISSUE THREAD

**Issue by DeerajTheepshi** [processing/processing-android#523]
How to Recreate issue : 
1. Switch to android mode
2. Open android->SdkUpdater
3. Close it before the updates are fetched. (This happens in case of slow internet connectivity)
4. The console, still shows a fetch process running. 

Priority: Minimum. This shouldn't be causing any other problems.

Ready to Work on it? : Yes

**Comment by SyamSundarKirubakaran** [comment]
I think that is the way it is intended to be.! In Android Studio, if SDK is being fetched over the network the user is blocked from performing any other activities on the IDE .i.e., Blocking state. But I think what Processing does is good.! Making it fetch in the background while having the instance of the older SDK for current builds. 

My Personal opinion would be to add a **Cancel** button to terminate the fetch instead of removing it from background.

@codeanticode @kfrajer Thoughts.!?

**Comment by mario-vimal** [comment]
I noticed this issue while closing the SDK updater. If no one is working on this, I would like to take this up. Is it fine if a Message Dialog is shown stating that a background process is running? Also stopping the fetch thread on confirmation? @codeanticode @DeerajTheepshi @kfrajer

**Comment by ranaaditya** [comment]
Hi @rupeshkumar22 , is this issue resolved or we are yet to implement it ?

Seems like we have already discussed this in **sdk updater and emulator bringup** issue catchup already.

Thanks,
rana !

**Comment by rupeshkumar22** [comment]
Hi @ranaaditya , this is yet to implement, Yes this is the same issue that we discussed. The major issue is that on startup of SDKUpdater UI, It crashes because the library (sdklib) used in SDKUpdater uses old java dependencies which have been removed in java 17, that we started using. I updated the sdklib and related methods in SDKUpdater and the issue was not removed. Seems like the recent versions of the library(sdklib) also use old imports of java. But it seems we can probably find a fix. #666 

Thanks,
Rupesh
