### ISSUE TITLE
Making a new PGraphics and displaying causes NullPointer

### ISSUE THREAD

**Issue by processing-bugs** [processing/processing-android#53]
<a href="https://github.com/GKFX"><img src="https://avatars.githubusercontent.com/u/5357642?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GKFX](https://github.com/GKFX)**
_Saturday May 31, 2014 at 12:19 GMT_
_Originally opened as https://github.com/processing/processing-android-archive/issues/68_

---

The simplest form of this is:

``` Java
PGraphics pg = createGraphics(100, 100);
pg.background(100); //optional
image(pg, 0, 0);
```

To rectify it, you need to type:

``` Java
PGraphics pg = createGraphics(100, 100);
pg.background(#ff0000); //optional
pg.loadPixels();
image(pg, 0, 0);
```

**Comment by Techy4198** [comment]
Why did this get left in the dust? The issue is most certainly still present.

**Comment by codeanticode** [comment]
Note that, in order to be able to use a PGraphics correctly, you need to call beginDraw()/enDraw(), as detailed in the [tutorials](https://processing.org/tutorials/rendering/) and [reference](https://processing.org/reference/PGraphics.html).

I'm able to run the following code without any errors:

```
PGraphics pg = createGraphics(100, 100);
pg.beginDraw();
pg.background(100);
pg.endDraw();
image(pg, 0, 0);
```

Please indicate in what specific situations you see the NPE error (also adding what version of the Android mode are you using, and device).

**Comment by Techy4198** [comment]
Looking back, I think my issue was actually more centered around trying to render a global PGraphics before it's been drawn to at all. I think I solved it by just drawing a background right after creating it. I guess I can see the reasoning behind an uninitialized canvas being partly treated as null.

**Comment by codeanticode** [comment]
That's right, before calling beginDraw()/endDraw() at least once, then the PGraphics is not properly initialized for rendering. I think this clarifies the issue, so it can be closed now.
