### ISSUE TITLE
Unable to build with Android Studio

### ISSUE THREAD

**Issue by NitishGadangi** [processing/processing-android#591]
This might be a lame doubt.
But someone, please help me in building the project.
I have imported it to Android Studio and facing this issue.
```ERROR: Unable to load class 'org.gradle.api.artifacts.transform.TransformAction'.```

**Steps to reproduce:**
import the project to AndroidStudio and Compile

**Comment by udhay24** [comment]
@NitishGadangi  i just figured out the steps to set-up the project working. just follow the steps in this documentation.
 https://github.com/processing/processing-android/wiki/Building-Processing-for-Android

you can use intellij as your IDE, since it is not an android project actually. I didn't see any purpose in using android studio.
