### ISSUE TITLE
SDK is not automatically downloaded

### ISSUE THREAD

**Issue by victordiaz** [processing/processing-android#600]
Using Windows 10, when I get the prompt to choose between select and download the SDK, if I press download it does not work.

I had in the past (years ago) similar issues and I wonder if it's maybe less confussing for the user to just download Android Studio. Or maybe to mantain a local copy of the tool chain that does not dissapear over time
(Just a thought)

**Comment by ranaaditya** [comment]
> Using Windows 10, when I get the prompt to choose between select and download the SDK, if I press download it does not work.
> 
> I had in the past (years ago) similar issues and I wonder if it's maybe less confussing for the user to just download Android Studio. Or maybe to mantain a local copy of the tool chain that does not dissapear over time
> (Just a thought)

Hi @victordiaz  may be the problem is in the path you are giving for sdk downloading, and using in IntelliJ IDE for using internally are **different.**

Can you provide necessary **screenshots** for this ?

**Comment by josefinHeilig** [comment]
Hi,
I had the same issue. 
I think the downloading does not work anymore because of a restructuring of the download page, which does not offer the direct download of sdks but only through the use of an sdkmanager.

I used the locate path button instead. First I downloaded Android Studio and then used the sdkmanager to install version 28 required by processing 3.5.4. 
Then the locate path button works typing the following path for me:
C:\Users\Josefin\AppData\Local\Android\Sdk\

This added the following line in preferences.txt :
android.sdk.path=C:\Users\Josefin\AppData\Local\Android\Sdk\

When I opened processing again and Adroid Mode just worked fine and did not ask for sdk again.

Alternatively to using Android Studio I found on  https://developer.android.com/studio/index.html#downloads under Command line tools only:
"If you do not need Android Studio, you can download the basic Android command line tools below. You can use the included sdkmanager to download other SDK packages."

Hope this helps others!

**Comment by codeanticode** [comment]
This should be solved with the latest release of the mode (4.2.0). Please confirm if SDK downloading still causes issues.

**Comment by codeanticode** [comment]
Haven't heard back was not able to reproduce this issue, so closing for now.
