### ISSUE TITLE
Targeting Android 11 required Signature V2 Signing.

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [processing/processing-android#646]
Currently, the packages are being exported with Signature V1 signing. According to the official android documentation [here](https://developer.android.com/about/versions/11/behavior-changes-11) -

`Apps that target Android 11 (API level 30) that are currently only signed using APK Signature Scheme v1 must now also be signed using APK Signature Scheme v2 or higher. Users can't install or update apps that are only signed with APK Signature Scheme v1 on devices that run Android 11.`

There is a need to provide the functionality to export the packages with V2 Signing, But first, need to make sure that it won't create [compatibility issues](https://github.com/processing/processing-android/issues/627).

Testings are required to verify the exported packages on Android 11 devices or emulators with build target version 11.

Below is one of the methods to check the Signature Version of the packages:

![SignV2Issue](https://user-images.githubusercontent.com/46577873/113518718-b2646b00-95a5-11eb-921d-750308c78f16.PNG)

**Comment by farhazulMullick** [comment]
After a successfull gradle sync why I cannot this application like simple android application on mobile
why I cannot run this appliction like other application on emulator

**Comment by rupesh-kumar-lpu** [comment]
@farhazulMullickHi, According to what I understand from your comment, Are you trying to build and install 'processing-android' project on an emulator through the Android Studio? If yes then this is not a native android app project which you can run on an emulator. The project builds the Processing Mode and related libraries i.e Processing Core, AR, and VR. For more information on building the project, you can refer to [this page](https://github.com/processing/processing-android/wiki/Building-Processing-for-Android).
Also, For such queries, I would recommend you to use the official community website of Processing Foundation https://discourse.processing.org/

**Comment by rupesh-kumar-lpu** [comment]
**References for V2 Signing**

Google Source Code for [V2 Signing](https://android.googlesource.com/platform/build/+/dd910c5/tools/signapk/src/com/android/signapk/ApkSignerV2.java)
More About [V2 Scheme](https://source.android.com/security/apksigning/v2)
[APKSigner]() from SDK.

**Comment by codeanticode** [comment]
I'd see this is critical because apps built with Processing won't be compatible with Android 11 devices unless V2 signing is supported.

**Comment by codeanticode** [comment]
@rupesh-kumar-lpu This one we still need to address, as far as I understand you have not included V2 signing in [your PR](https://github.com/processing/processing-android/pull/671), correct?

**Comment by rupesh-kumar-lpu** [comment]
Hi Andres, it's strange to get that play console error despite the code for the v2 scheme seems alright. 
Are we aligning the bundle after signing? Not sure if we really need to align bundle.
I'll try signing unsigned bundle manually with apksigner and will compare the packages.
Last time I generated universal apk from bundle generated from project and that worked fine on devices. I am looking into it and will inform at the earliest. 
After resolving this one, major implementation to work on would be to automate publishing of packages on central repository.
Thanks @codeanticode

**Comment by codeanticode** [comment]
Actually the signed_v2.aab was flagged as a corrupted zip file when I tried to upack using the command line tool unzip:

```
warning [test_release_signed_v2.zip]:  1574306 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [test_release_signed_v2.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

 I was mislead because I before used a GUI tool on Mac that was able to unpack it. When I get the file type with ```file test_release_signed_v2.zip``` it is recognized as a Java archive data (JAR)... so I guess the zipping step is what is missing/wrong. Which is actually encouraging :-)

**Comment by codeanticode** [comment]
@rupesh-kumar-lpu I thought this function was returning chunks already in zip format:

https://github.com/processing/processing-android/blob/master/mode/src/processing/mode/android/ApkSignerV2.java#L199

Since its doing this:

https://github.com/processing/processing-android/blob/master/mode/src/processing/mode/android/ApkSignerV2.java#L278

but maybe not? I will try zipping the resulting buffer, maybe that's the solution, if you have any other ideas please let me know.

**Comment by codeanticode** [comment]
With this change https://github.com/processing/processing-android/commit/67dcfab77724dabf328b77660ec9613c4fadd0f1 seems its closer but not quite there yet, because the resulting aab file still not a valid zip file, but the error from unzip is different:

```
unzip test_release_signed_v2.aab
Archive:  test_release_signed_v2.aab
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of test_release_signed_v2.aab or
        test_release_signed_v2.aab.zip, and cannot find test_release_signed_v2.aab.ZIP, period.
```

Like it is not properly closed or something (End-of-central-directory signature not found). Any help much appreciated :-)

**Comment by rupesh-kumar-lpu** [comment]
Hi @codeanticode, The APKSigner sources link I shared was for APK Signer earlier as we did not have support for AAB at that time. I think apkSigner is only for signing APK, and for signing AAB we need to sign it either using Java JarSigner present in the java bin folder along with javac and java binaries or [bundletool](https://developer.android.com/studio/command-line/bundletool) / [bundletool sources](https://github.com/google/bundletool)

"If you want to sign an app bundle from the command line, you can use jarsigner. If instead you want to sign an APK, you need to use zipalign and apksigner as described below."
The above is mentioned [here](https://developer.android.com/studio/build/building-cmdline) officially on Android Docs


We can also use the java implementation of JarSigner [JarSigner.java](https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/jdk.jartool/share/classes/jdk/security/jarsigner/JarSigner.java) from open JDK or directly execute the binary by process builder task(Seems a faster option to implement)

Let me know your views on implementing @codeanticode @ranaaditya 
Thanks!

**Comment by codeanticode** [comment]
Ok I see, aab is actually a different file format from apk, as far as I can tell from Google's [official docs](https://developer.android.com/guide/app-bundle) and other [online resources](https://stackoverflow.com/questions/52059339/difference-between-apk-apk-and-app-bundle-aab), is that right? I missed that fact originally.

In any case, I think that it could be better just to use the JarSigner & bundletool from the JDK/Android SDK respectively. Sounds like executing their binaries with a process builder task from the Android mode should work, since JarSigner is included in the copy of the OpenJDK bundled with Processing, and I'd imagine that bundletool comes with the Android SDK download as well.

**Comment by rupesh-kumar-lpu** [comment]
Yes, it's a different format I also missed the fact, and yes bundle tool is included in SDK as well. Can I start working on it with process builder if you are not working on the same? @codeanticode

**Comment by codeanticode** [comment]
@rupesh-kumar-lpu yes if you could look into it, it would be amazing, thank you! I'm trying to at least push one last update of the Android mode for Processing 3 including this and few other critical updates before switching to support the Android mode only for Processing 4.

**Comment by rupesh-kumar-lpu** [comment]
It's great to know Android Mode is moving to Processing 4. I am looking forward to working on the current signing implementation.

**Comment by codeanticode** [comment]
Awesome! Maybe you can start by assembling the command line calls using JarSigner and bundletool needed to generate the signed packages, so then we can figure out how to properly run using the process builder from the mode itself.

**Comment by codeanticode** [comment]
V1 signing seems to be enough once setting target SDK to 30:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/62246/162643336-f9d970fd-d6db-43d4-80f8-1cbd5a9bc496.png">

**Comment by codeanticode** [comment]
The signing can be done as part of the Gradle build task, see this example:

https://medium.com/automating-react-native-app-release-to-google-play/create-upload-key-and-apps-release-bundle-aab-file-4bf4a17e19a1

Implemented with this commit https://github.com/processing/processing-android/commit/11865cd69b062092f72e4c0f4938f7da6e9d9102
