### ISSUE TITLE
Exported Android Projects cannot be properly imported into Android Studio

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#653]
The Gradle project file generated by the mode does not show with the full structure of an Android project in Android Studio, a warning message informs that the project does not use the Gradle build system:

![image](https://user-images.githubusercontent.com/62246/116604403-0f7ce380-a8fc-11eb-928d-fd2c4e490a4f.png)

**Comment by rupesh-kumar-lpu** [comment]
Hi @codeanticode, I tried importing the project on windows and didn't face this issue. Can I get some more information on this to regenerate the issue?
Thanks,
Rupesh

**Comment by codeanticode** [comment]
I exported a sketch using the  "Export Android Project" option under the File menu, and then tried to import project from Android Studio. I used AS 4.1.3. Thank you!

**Comment by rupeshkumar22** [comment]
I confirm that wrappers files and gradlew command issues can be fixed with #747 for older Android Studio using older gradle versions, but to my surprise, I tried importing the project exported from Android Mode in the latest Android Studio Flamingo and the gradle build corrected the wrapper files i.e included the `gradle-wrapper.jar` by itself after importing which is not currently part of Export Android Project in Android Mode as of now. 
I confirm exported project from Android Mode working fine on the latest Android Studio Flamingo 2022.2.1

**Comment by codeanticode** [comment]
@rupeshkumar22 thanks for confirming that the export functionality is working!

Actually, the project export for AR sketches was broken, but this commit fixed it https://github.com/processing/processing-android/commit/bdde55ade6549fa7f28abf73169e37b61860cc5c :-)
