### ISSUE TITLE
SDK license acceptance dialog does not work with SDK 30

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#676]
Updating the android-platform to 30 in version.properties results in a non-functional mode: the SDK downloads fine but then the license does not get accepted even if the user press accept in the license dialog that pops up right after concluding download.

**Comment by rupesh-kumar-lpu** [comment]
I change the platform to 30 in 'version.properties' and then I build the Android Mode distribution. I hide any pre-existing SDK or Android_SDK home if available. Now after initiating a run of processing base class with Android Mode VM arguments. I see 'Android SDK not valid' box with options. After selecting download SDK it downloads the SDK to hundred percent and then I see the license box and after selecting yes, It says SDK installation successful and opens the PDE. I see 'no updates' on selecting sdk updater in PDE. So basically I am not able to reproduce the issue. Are you using linux @codeanticode because I am using windows? Can you provide more details on this if I am missing any step to reproduce this? Thanks!

**Comment by codeanticode** [comment]
I'm doing most of the development on mac, but I can test on Windows and Linux. I don't think I have checked if this issue affects the latter two platforms.

**Comment by codeanticode** [comment]
Actually, I may have been wrong when reporting this issue originally. I just re-downloaded the SDK after updating the mode to use SDK 30, and everything went well, including the license accept step, exporting an bundle, and the uploading to the Play Console with target SDK 30:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/62246/162643277-264b18a3-9a37-4d21-8a04-62ffa077768e.png">

So I'm going to label this issue as invalid and close it. We can revisit if it comes up again on mac or other platform.
