### ISSUE TITLE
Export Android project is broken

### ISSUE THREAD

**Issue by codeanticode** [processing/processing-android#741]
The exported gradle project does not build with gradle wrapper, seem to be missing files (only gradle-wrapper.properties is inside /wrapper)

**Comment by rupeshkumar22** [comment]
@codeanticode 
The exported project through Android Mode got imported to Android Studio and build was successful.
The issue is with running `gradlew build` in command line in exported project's directory.

I conclude the following from the analysis-

The current structure of Exported Project is-

>  android->app
>  android->wrapper->gradle-wrapper.properties

Whereas it must look similar to the following-
>  android->app
>  android->gradle->wrapper->gradle-wrapper.properties
>  android->gradle->wrapper->gradle-wrapper.jar(Currently missing in Exported project)

After changing the structure a bit the build was working fine on the command line.
@codeanticode @ranaaditya  let me know if we are fine with changing the export structure according to this, I will create a PR to apply the changes.

**Comment by ranaaditya** [comment]
> @codeanticode 
> The exported project through Android Mode got imported to Android Studio and build was successful.
> The issue is with running `gradlew build` in command line in exported project's directory.
> 
> I conclude the following from the analysis-
> 
> The current structure of Exported Project is-
> 
> >  android->app
> >  android->wrapper->gradle-wrapper.properties
> 
> Whereas it must look similar to the following-
> >  android->app
> >  android->gradle->wrapper->gradle-wrapper.properties
> >  android->gradle->wrapper->gradle-wrapper.jar(Currently missing in Exported project)
> 
> After changing the structure a bit the build was working fine on the command line.
> @codeanticode @ranaaditya  let me know if we are fine with changing the export structure according to this, I will create a PR to apply the changes.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Hi @rupeshkumar22 , great to hear that you figured out the issue.

Please make a draft PR with changes, will review and see if we could have those changes.

Thanks,
Aditya Rana
